config/routes.rb
Rails.application.routes.draw do
  
  resources :users do 
    resources :admin
  end
  resources :recipes do 
    resources :comments, except: [:destroy]
    get '/favorite' => 'favorites#show'
    post '/favorite' => 'favorites#update'
    post '/comments' => 'comments#create'
  end

  resources :comments, only: [:destroy]
    
  root to: 'recipes#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get 'auth/google_oauth2/callback' => 'sessions#create'
  

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get 'recipes_sorted_by_favorite' => 'recipes#sorted_favorite'
  get 'recipes_sorted_by_cook_time' => 'recipes#sorted_cook_time'
  get 'recipes_sorted_by_newest' => 'recipes#sorted_newest'

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user

  validates_inclusion_of :rating, :in => 1..5, message: "is between 1-5"

  def user_name
    user.name
  end

  def time
    created_at.strftime("%l:%M %P %B %e, %Y")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    @comment = Comment.new
  end

  def show
    comment = Comment.find_by(user: current_user, recipe: find_by_recipe_id)
    respond_to do |f|        
      f.json {render json: comment}       
    end 
  end

  def create
    if logged_in?
      comment = Comment.new(comment_params)
      comment.recipe = find_by_recipe_id
      comment.user = current_user
      if comment.save
        respond_to do |f|     
          f.json {render json: comment}        
        end 
      end
    else 
      redirect_to login_path, alert: "You must be logged in to comment"
    end
  end

  def edit
    @comment = find_by_id(Comment)
  end

  def update
    comment = find_by_id(Comment)
    comment.update(comment_params)
    redirect_to recipe_path(comment.recipe), notice: "Your comment has been updated"
  end

  def destroy
    id = params["id"].to_i
    comment = Comment.find_by(id: id)
    comment.delete
    flash[:notice] = "Comment has been deleted"
  end


  private
  def comment_params
     params.require(:comment).permit(:rating, :description)
  end




end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
  <%= form_for [recipe, comment] do |f| %>
    <%= render 'layouts/form_errors', form: comment %>
    <div>Rating: (1-5)</div> <div><%= f.text_field :rating %></div>
    <div>Description</div> <div><%= f.text_field :description %></div>
    <%= f.submit data: { disable_with: false }%>
<% end %>

app/views/comments/_list_comments.html.erb
<% comments.each do |comment| %>
  <div class="comments">
  <h3 class="cheading"><%= link_to comment.user.name, user_path(comment.user) %><%= " gives #{comment.rating} stars on #{comment.time}"%></h3>
  <p class="cdescription"><%= comment.description %></p>
  <% if current_page?("/users/#{comment.user.id}") && logged_in? %>
    <p><%= link_to "Recipe: #{comment.recipe.name}", recipe_path(comment.recipe) %></p>
  <% end %>

  <%= link_to "Edit", edit_recipe_comment_path(comment.recipe, comment) if logged_in? && current_user.can_edit?(comment)%>

  <%= link_to "Delete", comment_path(comment), class: 'dcomment' if logged_in? && current_user.can_delete?(comment)%>
  </div>
<% end %>

<script id="comment-template" type="text/x-handlebars-template">
  <div class="comments">
    <h3 class="cheading"><a href="/users/{{userId}}">{{userName}}</a> gives {{rating}} stars Just Now</h3>
    <p class="cdescription">{{description}}</p>

    <a href="/recipes/{{recipeId}}/comments/{{id}}/edit">Edit</a>

    <a href="/comments/{{id}}/">Delete</a>
    <br />
  </div>
 </script>

app/views/comments/edit.html.erb
<%= render 'comments/form', comment: @comment, recipe: @comment.recipe %>

app/views/comments/new.html.erb
<%= render 'comments/form', comment: @comment, recipe: @recipe %>