config/routes.rb
Rails.application.routes.draw do
  
  resources :users do 
    resources :admin
  end
  resources :recipes do 
    resources :comments, except: [:destroy]
    get '/favorite' => 'favorites#show'
    post '/favorite' => 'favorites#update'
    post '/comments' => 'comments#create'
  end

  resources :comments, only: [:destroy]
    
  root to: 'recipes#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get 'auth/google_oauth2/callback' => 'sessions#create'
  

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get 'recipes_sorted_by_favorite' => 'recipes#sorted_favorite'
  get 'recipes_sorted_by_cook_time' => 'recipes#sorted_cook_time'
  get 'recipes_sorted_by_newest' => 'recipes#sorted_newest'

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :favorites
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  validates :name, uniqueness: true
  validates :name, presence: true

  accepts_nested_attributes_for :ingredients, reject_if: lambda {|attributes| attributes['name'].blank?}
  accepts_nested_attributes_for :recipe_ingredients, reject_if: lambda {|attributes| attributes['name'].blank?}

  scope :fastest, -> { order("time_in_minutes ASC") }

  include ActionView::Helpers::TextHelper
  
  def user_name
    user.name
  end

  def self.newest(number = all.size)
    order("ID DESC").limit(number)
  end

  def favorite?(current_user)
   current_user && self.favorites.find_by(user_id: current_user.id)
  end

  def comments_size
    pluralize(comments.size, "Comment")
  end

  def delete_ingredients_from_recipe
      ingredients.size.times do
      ingredient = RecipeIngredient.find_by(recipe_id: self.id)
      ingredient.delete
    end
  end

  def add_ingredients_to_recipe(params)

    delete_ingredients_from_recipe
    
    params[:recipe_ingredients_attributes].each do |k, recipe_ingredient|

      if recipe_ingredient[:ingredient][:name].present?
        ingredient_name = recipe_ingredient[:ingredient][:name].downcase
        ingredient = Ingredient.find_or_create_by(name: ingredient_name)
      elsif recipe_ingredient[:ingredient_id].present?
        ingredient = Ingredient.find_by(id: recipe_ingredient[:ingredient_id])
      end

      if recipe_ingredient[:quantity].present?
        RecipeIngredient.create(quantity: recipe_ingredient[:quantity], ingredient_id: ingredient.id, recipe_id: self.id )
      end

    end

  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def home
    @recipes = Recipe.newest(5)
    @favorites = Favorite.top_favorited(3)
  end

  def new
    @recipe = Recipe.new
    @ingredients = 6.times.collect { @recipe.recipe_ingredients.build }
  end


  def create
    recipe = current_user.recipes.new(recipe_params)
    if recipe.save
      recipe.add_ingredients_to_recipe(recipe_ingredient_params)
      redirect_to recipe_path(recipe), notice: "Your recipe has successfully been added"
    else
      @recipe = Recipe.new
      redirect_to new_recipe_path, alert: recipe.errors.full_messages.each {|m| m}.join
    end
  end

  def edit
    @recipe = find_by_id(Recipe)
    @i = 3.times.collect { @recipe.recipe_ingredients.build }
  end

  def update
    recipe = find_by_id(Recipe)
    if recipe.update(recipe_params)
      recipe.add_ingredients_to_recipe(recipe_ingredient_params)
      redirect_to recipe_path(recipe), notice: "Your recipe has successfully been updated"
    else 
      redirect_to new_recipe_path, alert: recipe.errors.full_messages.each {|m| m}.join
    end
  end

  def show
    @recipe = find_by_id(Recipe) || Recipe.first
      respond_to do |format|
        format.html  { render :show }
        format.json { render json: @recipe}
      end
  end

  def next
    binding.pry
    if @recipe = Recipe.find_by(id: (params[:id] + 1))
      binding.pry
    else
      @recipe = Recipe.first
    end
  end

  def destroy
    if authorized_admin
      # recipe = find_by_id(Recipe)
      # recipe.delete
      redirect_to root_path
    end
  end

  def sorted_favorite
    recipes = Favorite.get_favorite_recipes_in_order
    render json: recipes
  end

  def sorted_cook_time
    recipes = Recipe.fastest
    render json: recipes
  end

  def sorted_newest
    recipes = Recipe.newest
    render json: recipes
  end

  private 

  def recipe_params
    params.require(:recipe).permit(:name, :time_in_minutes, :instructions)
  end

  def recipe_ingredient_params
    params.require(:recipe).permit(recipe_ingredients_attributes: [:quantity, :ingredient_id, ingredient: [:name]])
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_favorites_listed.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <h3> favorites list </h3>
    </div>
    <% favorites.each do |popular|%>
        <div class="col-xs-8 col-xs-offset-2">
          <div class="well well-lg">
            <%= render 'recipes/list_recipes', recipe: popular.recipe %>
          </div>
        </div>
    <% end %>
</div>

app/views/recipes/_form.html.erb
<%= form_for recipe do |f| %>
<div class="row">
    <div class="col-xs-12">
        <div class="form-group">
            <%= render 'layouts/form_errors', form: recipe %>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :Recipe_Name %>
            </div>
            <div class="col-sm-10">
                <%= f.text_field :name , class: "form-control", placeholder: "Recipe Name", autofocus: true%>
            </div>
            <br><br>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :Cook_Time %>
            </div>
            <div class="col-sm-10">
                <%= f.text_field :time_in_minutes , class: "form-control", placeholder: "Cook Time", autofocus: true%>
            </div>
            <br><br>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :Instructions %>
            </div>
            <div class="col-sm-10">
                <%= f.text_area :instructions , class: "form-control", placeholder: "Instructions", autofocus: true%>
            </div>
        </div>
    </div>
    <br><br>
    <div class="col-xs-12">
        <h3 style="margin-left:20px">Add Ingredients:</h3>
    </div>
    <div class="col-xs-12">
        <div class="form-group">
            <div>
                <%= f.fields_for :recipe_ingredients, @ingredients do |recipe_ingredient| %>
            <div>
            <div class="control-label col-sm-4">
                <div class="control-label col-sm-2 pr">
                Quantity:
                </div>
                <div class="col-sm-10 ml">
                 <%= recipe_ingredient.text_field :quantity ,class: "form-control"%>
                </div>
            </div>
            <div class="control-label col-sm-4">
                <div class="control-label col-sm-2 pr">Select:</div>
                <div class="col-sm-10 ml">
                <%= recipe_ingredient.collection_select :ingredient_id, Ingredient.order('name ASC').all, :id, :name, include_blank: 'Select Ingredient' ,class:'form-control'%>
                </div>
            </div>
            <div class="control-label col-sm-4 mg">
                <div class="control-label col-sm-2 pr">
                    Create:
                </div>
                <div class="col-sm-10 ml">
                    <%= recipe_ingredient.fields_for :ingredient, recipe.ingredients.build do |ingredient| %>
                    <%= ingredient.text_field :name ,class: "form-control"%>
                </div>
                <% end %>
            </div>
            <% end %>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-5 col-sm-4">
                <%= f.submit "Submit", class: 'btn btn-primary btn-large'%>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/recipes/_list_recipes.html.erb
<div class="article-title">
    <%= link_to recipe.name, recipe_path(recipe)%>
</div>

<div class="article-body">
    <%= recipe.time_in_minutes %> minutes until it's ready | By:
    <%= link_to recipe.user_name, user_path(recipe.user)%> |
    <%= recipe.comments_size%> |
    <%= render 'favorites/favorited', recipe: recipe%>
</div>

<div class="article-actions">
    <% if !current_page?('/') && logged_in? %>
      <%= link_to "Edit", edit_recipe_path(recipe) if current_user.can_edit?(recipe)%> | <%= link_to "Delete", recipe_path(recipe), method: :delete if current_user.can_delete?(recipe)%>
    <% end %>
</div>

<script id="recipe-template" type="text/x-handlebars-template">
  <div id="each-recipes">
    <ul>
      <li><h2><a href="/recipes/{{recipeId}}">{{name}}</a></h2></li>
      <li>{{timeInMinutes}} minutes until it's ready | By: <a href="/users/{{userId}}">{{userName}}</a> </li>
    </ul>
  </div>
</script>

app/views/recipes/_recipe_details.html.erb
<div id="recipe-detail-header">
  <h1><%= recipe.name %></h1>
  <h2><%= recipe.time_in_minutes %> minutes until it's ready | By: <%= link_to recipe.user_name, user_path(recipe.user)%></h2>

<%= render 'favorites/favorited', recipe: recipe%>
</div>

<div id="recipe-detail-ingredients"><%= render 'ingredients/list_ingredients', recipe: recipe %></div>

<div id="recipe-details-bottom">

  <h4><%= recipe.instructions %></h4>

  <%= link_to "Edit", edit_recipe_path(recipe) if logged_in? && current_user.can_edit?(recipe)%>

  <%= link_to "Delete", recipe_path(recipe), method: :delete if logged_in? && current_user.can_delete?(recipe)%>

  <%= link_to "Next", "#", class: "next_recipe", data: { recipeId: recipe.id }%>

</div>

<script id="recipedetailheader-template" type="text/x-handlebars-template">
    <h1>{{name}}</h1>
<h2>{{timeInMinutes}} minutes until it's ready | By: <a href="/users/{{userId}}">{{userName}}</a></h2>
</script>
<script id="recipeingredients-template" type="text/x-handlebars-template">
<ul>  
    {{#each this}}
    <li>{{quantity}} {{name}}</li>
    {{/each}}
</ul>
</script>

<script id="recipedetailsbottom-template" type="text/x-handlebars-template">
<h4>{{instructions}}</h4>

<a class="next_recipe" data-recipeid="{{recipeId}}" href="#">Next</a>
</script>

<script id="recipedetailcomments-template" type="text/x-handlebars-template">
  <div>
    {{#each this}}
      <h3 class="cheading"><a href="/users/{{userId}}">{{userName}}</a> gives {{rating}} stars</h3>
      <p class="cdescription">{{description}}</p>
    {{/each}}
  </div>
</script>

<script id="recipedetailscommentform-template" type="text/x-handlebars-template">
  <div>
    <form class="new_comment" id="new_comment" action="/recipes/{{id}}/comments" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="rmz27HBdgcx+vXUiInd9sW5P4SF35PeVWjNz3xqmu6nVEHMWBuexkVvdd7nPTXqCiz5Xx6vuex1ljgpHRbiWTQ==">
      
      <div>Rating: (1-5)</div> <div><input type="text" name="comment[rating]" id="comment_rating"></div>
      <div>Description</div> <div><input type="text" name="comment[description]" id="comment_description"></div>
      <input type="submit" name="commit" value="Create Comment">
    </form>
  </div>
</script>

<script id="comment-template" type="text/x-handlebars-template">
  <div class="comments">
    <h3 class="cheading"><a href="/users/{{userId}}">{{userName}}</a> gives {{rating}} stars Just Now</h3>
    <p class="cdescription">{{description}}</p>

    <a href="/recipes/{{recipeId}}/comments/{{id}}/edit">Edit</a>

    <a class="dcomment" href="comments/{{id}}">Delete</a>
    <br />
  </div>
 </script>

app/views/recipes/_recipes_listed.html.erb
<div class="well well-lg">
  <% recipes.each do |recipe|%>
    <%= render 'recipes/list_recipes', recipe: recipe%>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<h1>Update Your Recipe</h1>
<%= render 'recipes/form', recipe: @recipe, ingredient: @recipe.recipe_ingredients %>

app/views/recipes/home.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <h1>Top Trending Recipes:</h1>
    </div>
</div>
<% if @recipes %>
    <%= render 'recipes/favorites_listed', favorites: @favorites %>

    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <h3>Our 5 latest Recipes</h3>
            <%= render 'recipes/recipes_listed', recipes: @recipes %>
        </div>
    </div>
<% else %>
  Sign Up and help us add some recipes to our database!
<% end %>

app/views/recipes/new.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <h1>Add your own recipe now!</h1>
    </div>
</div>

<div class="col-xs-8 col-xs-offset-2">
  <div class="well well-lg">
    <%= render 'recipes/form', recipe: @recipe, ingredient: @ingredients %>
  </div>
</div>

app/views/recipes/recipes.html.erb
<h1><%= @sort_kind %></h1>

<% if @recipes %>
  <%= render 'recipes/recipes_listed', recipes: @recipes %>
<% elsif @favorites %>
  <%= render 'recipes/favorites_listed', favorites: @favorites %>
<% end %>

app/views/recipes/show.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <%= render 'recipes/recipe_details', recipe: @recipe %>
    </div>
</div>

<div class="row" id="show-comments">
    <div class="col-xs-8 col-xs-offset-2">
        <%= render 'recipes/recipe_details', recipe: @recipe %>
    </div>
</div>