config/routes.rb
Rails.application.routes.draw do
  
  resources :users do 
    resources :admin
  end
  resources :recipes do 
    resources :comments, except: [:destroy]
    get '/favorite' => 'favorites#show'
    post '/favorite' => 'favorites#update'
    post '/comments' => 'comments#create'
  end

  resources :comments, only: [:destroy]
    
  root to: 'recipes#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get 'auth/google_oauth2/callback' => 'sessions#create'
  

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get 'recipes_sorted_by_favorite' => 'recipes#sorted_favorite'
  get 'recipes_sorted_by_cook_time' => 'recipes#sorted_cook_time'
  get 'recipes_sorted_by_newest' => 'recipes#sorted_newest'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes
  has_many :comments
  has_many :favorites
  has_many :ingredients, through: :recipes

  validates :name, uniqueness: true
  validates :name, presence: true

  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { minimum: 6 },
                       :unless => :already_has_password?

  has_secure_password

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
  
  def admin?
    admin
  end

  def can_edit?(class_type)
    if class_type.is_a?(User)
      self == class_type || admin?
    else
      self == class_type.user || admin?
    end
  end

  def can_delete?(class_type)
    case class_type
    when User
      admin?
    when Recipe
      admin?
    when Ingredient
      admin?
    when Comment
      can_edit?(class_type)
    end
  end

  def owns?(id)
    self.id == id.to_i
  end

  private

  def already_has_password?
    !self.password_digest.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorized, except: [:new, :create, :show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "You have successfully signed up"
    else
      render 'new'
    end
  end

  def edit
    @user = find_by_id(User)
  end

  def update
    @user = find_by_id(User)
    redirect_to request.referer || root_path, alert: "You cannot update this user" unless current_user.can_edit?(@user)
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have successfully updated #{@user.name}"
    else
      render :edit
    end
  end

  def show
    @user = find_by_id(User)
    @recipes = @user.recipes 
    @comments = @user.comments
    @favorites = @user.favorites
    @recipe = Recipe.new
    @ingredients = 6.times.map { @recipe.recipe_ingredients.build }
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :admin)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <div>Name:</div> <div><%= f.text_field :name %></div>
  <div>Password: (minimum 6 characters)</div> <div><%= f.password_field :password %></div>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <%= render 'layouts/form_errors', form: @user %>
  <%= render 'form', f: f %>
<%= f.submit "Submit" %>
<% end %>

app/views/users/new.html.erb
<div class="row">
    <div class="col-xs-4 col-xs-offset-4">
        <h3>Signup!</h3>
    </div>

    <%= form_for @user do |f| %>
    <div class="row">
        <div class="col-xs-4 col-xs-offset-4">
            <%= render 'layouts/form_errors', form: @user %>
              <%= render 'form', f: f %>
              <div>Password Confirmation:</div> <div><%= f.password_field :password_confirmation %></div>
              <%= f.submit "Submit" %>
        </div>
    </div>
    <% end %>

</div>

app/views/users/show.html.erb
<% if @recipes.first %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <h3>Recipes by: <%= @user.name %></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <%= render 'recipes/recipes_listed', recipes: @recipes %>
        </div>
    </div>
<% end %>
<% if logged_in? && current_user.owns?(params[:id])%>
  <% if @favorites.first %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <h3>Here are your favorite Recipes:</h3>
        </div>
    </div>
    <%= render 'recipes/favorites_listed', favorites: @favorites %>
  <% end %>
  <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
          <h1>Add your own recipe now!</h1>
      </div>
  </div>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
            <%= render 'recipes/form', recipe: @recipe, ingredient: @ingredients %>
        </div>
    </div>
  </div>

  <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
          <h3><%= link_to "Make Other Users Admins", user_admin_index_path(current_user) if current_user.admin?%></h3>
      </div>
  </div>
<% end %>