config/routes.rb
Rails.application.routes.draw do
  
  resources :users do 
    resources :admin
  end
  resources :recipes do 
    resources :comments, except: [:destroy]
    get '/favorite' => 'favorites#show'
    post '/favorite' => 'favorites#update'
    post '/comments' => 'comments#create'
  end

  resources :comments, only: [:destroy]
    
  root to: 'recipes#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get 'auth/google_oauth2/callback' => 'sessions#create'
  

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get 'recipes_sorted_by_favorite' => 'recipes#sorted_favorite'
  get 'recipes_sorted_by_cook_time' => 'recipes#sorted_cook_time'
  get 'recipes_sorted_by_newest' => 'recipes#sorted_newest'

end

app/views/layouts/_errors.html.erb
  <% if alert %>
    <div id="notice_wrapper" class="alert">
      <p class="alert"><%= alert %></p>
    </div>
  <% elsif notice %>
    <div id="notice_wrapper">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>

app/views/layouts/_form_errors.html.erb
<% if form.errors.any? %>
  <div id="notice_wrapper" class="alert">
    <h3>There were some errors:</h3>
    <ul>
      <% form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<navbar>
  <%= link_to "Home", root_path %>
  <%if logged_in? %>
    <%= link_to "Sign out", logout_path, method: :delete %>
    <%= link_to "Add Recipe", new_recipe_path %>
    <%= link_to "Hi, #{current_user.name}", user_path(current_user) %>
  <% else %>
    <%= link_to "Sign in", login_path %>
    <%= link_to "Sign up", signup_path %>
  <%end%>
</navbar>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Awesome Recipe", root_path, class: "navbar-brand", id: "logo" %>
      <%if logged_in? %>
          <%= link_to "Hi, #{current_user.name}", user_path(current_user) , class: 'btn btn-primary btn-warning logbtn'%>
          <%= link_to "Add Recipe", new_recipe_path , class: 'btn btn-primary btn-success logbtn'%>
      <%end%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav" id="sort-recipes-by">
      <li><%= link_to "All Recipes From New To Old", recipes_sorted_by_newest_path %></li>
      <li><%= link_to "Sort by Fastest Recipes", recipes_sorted_by_cook_time_path %></li>
      <li><%= link_to "All Recipes From Most Popular", recipes_sorted_by_favorite_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <%if logged_in? %>
            <%= link_to "Sign out", logout_path, method: :delete , class: 'btn btn-primary btn-danger logbtn'%>
          <% else %>
          <%= link_to "Sign in", login_path , class: 'btn btn-primary btn-large logbtn'%>
          <%= link_to "Sign up", signup_path , class: 'btn btn-primary btn-large logbtn' %>
         <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <!--
    <%= render 'layouts/navbar' %>
    -->
    <%= render 'layouts/errors' %>

    <%= yield %>
  </body>
</html>